In [1]:
import numpy as np

In [2]:
array1d = np.array([1, 2, 3, 4, 5])

In [3]:
array2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [4]:
array1d[0]

np.int64(1)

In [5]:
array1d[-1]

np.int64(5)

In [13]:
array2d[1][2]

np.int64(6)

In [14]:
array2d[1,2]

np.int64(6)

In [15]:
array1d[1:4]

array([2, 3, 4])

In [16]:
array2d[1,:]

array([4, 5, 6])

In [17]:
array2d[1,1:3]

array([5, 6])

In [18]:
array2d[:,1]

array([2, 5, 8])

In [19]:
array2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [20]:
array1d > 3

array([False, False, False,  True,  True])

In [21]:
array2d % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])